version: "3.8"
services:
  db:
    image: postgres:15
    container_name: meu-postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - minha-rede

volumes:
  postgres-data:

networks:
  minha-rede:
    driver: bridge
